server:
  port: 8080

spring:
  application:
    name: ORGCONNECT-MANAGEMENT
  datasource:
    url: jdbc:mysql://localhost:3306/orgconnect_management
    username: admin
    password : admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect
    hibernate:     
      ddl-auto: update
    show-sql: true